<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BBB6LF3" name="dnayuanceshi01.sizeyunsuanng" tests="12" failures="0" timestamp="2 Jan 2019 03:08:34 GMT" time="6.022" errors="3">
  <testcase name="Ccheng" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Dchu" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Dchu" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Ccheng" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Dchu" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Aadd" time="2.008" classname="dnayuanceshi01.sizeyunsuanng">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.Aadd() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.Aadd() didn't finish within the time-out 2000
	at org.testng.internal.thread.AtomicIntegerAdapter.incrementAndGet(AtomicIntegerAdapter.java:33)
	at org.testng.internal.BaseTestMethod.incrementCurrentInvocationCount(BaseTestMethod.java:669)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:69)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Aadd -->
  <testcase name="Aadd" time="2.002" classname="dnayuanceshi01.sizeyunsuanng">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.Aadd() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.Aadd() didn't finish within the time-out 2000
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Aadd -->
  <testcase name="Bjian" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Aadd" time="2.002" classname="dnayuanceshi01.sizeyunsuanng">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.Aadd() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.Aadd() didn't finish within the time-out 2000
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at java.lang.Throwable.<init>(Unknown Source)
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.InterruptedException.<init>(Unknown Source)
	at java.lang.Thread.sleep(Native Method)
	at dnayuanceshi01.sizeyunsuanng.Aadd(sizeyunsuanng.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Aadd -->
  <testcase name="Bjian" time="0.000" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Bjian" time="0.001" classname="dnayuanceshi01.sizeyunsuanng"/>
  <testcase name="Ccheng" time="0.003" classname="dnayuanceshi01.sizeyunsuanng"/>
</testsuite> <!-- dnayuanceshi01.sizeyunsuanng -->
